# Generated by Django 4.1.6 on 2023-02-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesInfo',
            fields=[
                ('employee_number', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('cédula', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('corre_electrónico', models.EmailField(max_length=254)),
                ('talla_zapatos', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/fotos/%Y/%m/%D/')),
                ('rut', models.FileField(blank=True, null=True, upload_to='media/ruts/%Y/%m/%D/')),
            ],
            options={
                'db_table': 'EmployeesInfo',
            },
        ),
    ]
