# Generated by Django 4.1.6 on 2023-02-10 19:11

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='celular',
            field=phone_field.models.PhoneField(blank=True, help_text='Ingresa el teléfono de contacto', max_length=31),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='corre_electrónico',
            field=models.EmailField(blank=True, help_text='Ingresa el correo electrónico', max_length=254),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='foto',
            field=models.ImageField(blank=True, help_text='Ingresa la foto del empleado', null=True, upload_to='media/fotos/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='nombre_completo',
            field=models.CharField(help_text='Ingresa el nombre completo', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='rut',
            field=models.FileField(blank=True, help_text='Ingresa el root del empleado', null=True, upload_to='media/ruts/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='talla_zapatos',
            field=models.IntegerField(blank=True),
        ),
    ]
