# Generated by Django 4.1.6 on 2023-02-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employeesinfo_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='celular',
            field=models.CharField(blank=True, help_text='Ingresa el teléfono de contacto', max_length=30),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='cédula',
            field=models.CharField(help_text='Ingresa la cédula', max_length=30),
        ),
    ]
