# Generated by Django 4.1.6 on 2023-02-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeesinfo_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='celular',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='corre_electrónico',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='cédula',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/fotos/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='rut',
            field=models.FileField(blank=True, null=True, upload_to='media/ruts/%Y/%m/%D/'),
        ),
    ]
