# Generated by Django 4.1.6 on 2023-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeesinfo_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='foto',
            field=models.ImageField(upload_to='media/fotos/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='rut',
            field=models.FileField(upload_to='media/ruts/%Y/%m/%D/'),
        ),
    ]
