# Generated by Django 4.1.6 on 2023-02-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employeesinfo_foto_alter_employeesinfo_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/fotos/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='rut',
            field=models.FileField(blank=True, null=True, upload_to='media/ruts/%Y/%m/%D/'),
        ),
    ]
