# Generated by Django 4.1.6 on 2023-02-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employeesinfo_foto_alter_employeesinfo_rut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesinfo',
            old_name='corre_electrónico',
            new_name='correo_electrónico',
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='rut',
            field=models.FileField(blank=True, null=True, upload_to='ruts/%Y/%m/%D/'),
        ),
    ]
