# Generated by Django 4.1.6 on 2023-02-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_rename_corre_electrónico_employeesinfo_correo_electrónico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesinfo',
            name='Género',
            field=models.CharField(choices=[('1', 'Hombre'), ('2', 'Mujer')], default=1, max_length=2),
        ),
        migrations.AlterModelTable(
            name='employeesinfo',
            table='employeesInfo',
        ),
    ]
