# Generated by Django 4.1.6 on 2023-02-12 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeesinfo_género_alter_employeesinfo_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesinfo',
            name='Género',
        ),
        migrations.RemoveField(
            model_name='employeesinfo',
            name='talla_zapatos',
        ),
        migrations.AddField(
            model_name='employeesinfo',
            name='declarante_de_renta',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No')], default=2, max_length=2),
        ),
        migrations.AddField(
            model_name='employeesinfo',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, default=datetime.date(2023, 2, 12)),
        ),
        migrations.AddField(
            model_name='employeesinfo',
            name='método_de_pago',
            field=models.CharField(choices=[('1', 'Cuenta Bancaria'), ('2', 'Nequi')], default=2, max_length=2),
        ),
        migrations.AddField(
            model_name='employeesinfo',
            name='número_de_cuenta',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
