# Generated by Django 4.1.6 on 2023-02-12 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employeesinfo_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 12, 20, 25, 15, 2890, tzinfo=datetime.timezone.utc)),
        ),
    ]
