# Generated by Django 4.1.6 on 2023-02-12 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employeesinfo_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
