# Generated by Django 4.1.6 on 2023-02-12 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employeesinfo_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='celular',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='correo_electrónico',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='cédula',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='fecha_de_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='nombre_completo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='número_de_cuenta',
            field=models.CharField(max_length=50),
        ),
    ]
