# Generated by Django 4.1.6 on 2023-02-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_employeesinfo_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesinfo',
            name='EPS',
            field=models.CharField(choices=[('1', 'Aliansalud'), ('2', 'Cafam EPS'), ('3', 'Capital Salud EPS'), ('4', 'Capresoca'), ('5', 'Colsubsidio'), ('6', 'COMFANDI'), ('7', 'Compensar'), ('8', 'Coomeva'), ('9', 'Coosalud'), ('10', 'EPS Sanitas'), ('11', 'EPS Sura'), ('12', 'Famisanar'), ('13', 'Medimás'), ('14', 'Mutual SER'), ('15', 'Nueva EPS'), ('16', 'Salud Total'), ('17', 'Savia Salud EPS'), ('18', 'SISBEN IV')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='employeesinfo',
            name='carnet_EPS',
            field=models.FileField(blank=True, null=True, upload_to='carnets/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='employeesinfo',
            name='fotocopia_cédula',
            field=models.FileField(blank=True, null=True, upload_to='cedulas/%Y/%m/%D/'),
        ),
    ]
