# Generated by Django 4.1.6 on 2023-02-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employeesinfo_eps_employeesinfo_carnet_eps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesinfo',
            name='dirección',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
