# Generated by Django 4.1.6 on 2023-02-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_employeesinfo_eps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='método_de_pago',
            field=models.CharField(choices=[('1', 'Cuenta Bancaria'), ('NEQUI', 'Nequi')], default='NEQUI', max_length=20),
        ),
    ]
