# Generated by Django 4.1.6 on 2023-02-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_alter_employeesinfo_método_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='EPS',
            field=models.CharField(choices=[('Aliansalud', 'Aliansalud'), ('Cafam EPS', 'Cafam EPS'), ('Capital Salud EPS', 'Capital Salud EPS'), ('Capresoca', 'Capresoca'), ('Colsubsidio', 'Colsubsidio'), ('COMFANDI', 'COMFANDI'), ('Compensar', 'Compensar'), ('Coomeva', 'Coomeva'), ('Coosalud', 'Coosalud'), ('EPS Sanitas', 'EPS Sanitas'), ('EPS Sura', 'EPS Sura'), ('Famisanar', 'Famisanar'), ('Medimás', 'Medimás'), ('Mutual SER', 'Mutual SER'), ('Nueva EPS', 'Nueva EPS'), ('Salud Total', 'Salud Total'), ('Savia Salud EPS', 'Savia Salud EPS'), ('SISBEN IV', 'SISBEN IV')], default='Aliansalud', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='declarante_de_renta',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='método_de_pago',
            field=models.CharField(choices=[('Cuenta Bancaria', 'Cuenta Bancaria'), ('NEQUI', 'Nequi')], default='NEQUI', max_length=20),
        ),
    ]
