# Generated by Django 4.1.6 on 2023-02-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_employeesinfo_eps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesinfo',
            name='método_de_pago',
            field=models.CharField(choices=[('Cuenta Bancaria', 'Cuenta Bancaria'), ('Nequi', 'Nequi')], default='Nequi', max_length=20),
        ),
    ]
