# Generated by Django 4.1.7 on 2023-02-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_number', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=18)),
                ('cédula', models.CharField(max_length=30)),
                ('dirección', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=30)),
                ('correo_electrónico', models.EmailField(max_length=254)),
                ('declarante_de_renta', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=20)),
                ('método_de_pago', models.CharField(choices=[('Cuenta Bancaria', 'Cuenta Bancaria'), ('Nequi', 'Nequi')], default='Nequi', max_length=20)),
                ('número_de_cuenta', models.CharField(max_length=50)),
                ('EPS', models.CharField(choices=[('Aliansalud', 'Aliansalud'), ('Cafam EPS', 'Cafam EPS'), ('Capital Salud EPS', 'Capital Salud EPS'), ('Capresoca', 'Capresoca'), ('Colsubsidio', 'Colsubsidio'), ('COMFANDI', 'COMFANDI'), ('Compensar', 'Compensar'), ('Coomeva', 'Coomeva'), ('Coosalud', 'Coosalud'), ('EPS Sanitas', 'EPS Sanitas'), ('EPS Sura', 'EPS Sura'), ('Famisanar', 'Famisanar'), ('Medimás', 'Medimás'), ('Mutual SER', 'Mutual SER'), ('Nueva EPS', 'Nueva EPS'), ('Salud Total', 'Salud Total'), ('Savia Salud EPS', 'Savia Salud EPS'), ('SISBEN IV', 'SISBEN IV')], default='Aliansalud', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='employee_photos/%Y/%m/%D/')),
                ('fotocopia_cédula', models.FileField(blank=True, null=True, upload_to='cedulas/%Y/%m/%D/')),
                ('carnet_EPS', models.FileField(blank=True, null=True, upload_to='carnets/%Y/%m/%D/')),
                ('rut', models.FileField(blank=True, null=True, upload_to='ruts/%Y/%m/%D/')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
