# Generated by Django 4.1.5 on 2023-02-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0002_alter_employees_carnet_eps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/employee_photos/%Y/%m/%D/'),
        ),
    ]
